/**
  * Generated by IntelliJ-IDEA Scala plugin.
  * Adds settings when starting sbt from IDEA.
  * Manual changes to this file will be lost.
  *
  * scala.collection.Seq(
  *   resolvers += Resolver.file("intellij-scala-plugin", file(raw"/Users/david/Library/Application Support/IdeaIC2019.1/Scala/repo"))(Resolver.ivyStylePatterns),
  *
  * addSbtPlugin("org.jetbrains" % "sbt-structure-extractor" % "2018.2.1+4-88400d3f"),
  * addSbtPlugin("org.jetbrains" % "sbt-idea-shell" % "2018.3"),
  * addSbtPlugin("org.jetbrains" % "sbt-idea-compiler-indices" % "0.1.3")
  */

resolvers += Resolver.url("jetbrains-bintray",
  url("https://dl.bintray.com/jetbrains/sbt-plugins/"))(Resolver.ivyStylePatterns)

addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.1")
addSbtPlugin("org.jetbrains" % "sbt-idea-plugin" % "3.14.3")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.11.0")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.0.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")

libraryDependencies ++= Seq("org.apache.commons" % "commons-text" % "1.8")
